MicrosoftDocs/CommunityToolkit

docs/maui/TOC.yml
docs/maui/converters/is-list-not-null-or-empty-converter.md
docs/maui/converters/is-list-null-or-empty-converter.md

Documentation added for .NET MAUI Community Toolkit - `[Proposal] ListIsNullOrEmpty Converters` <https://github.com/CommunityToolkit/Maui/issues/69>

IsListNullOrEmptyConverter documentation

---

docs/maui/TOC.yml
docs/maui/converters/equal-converter.md
docs/maui/converters/is-list-not-null-or-empty-converter.md
docs/maui/converters/is-list-null-or-empty-converter.md
docs/maui/converters/not-equal-converter.md

- `[Proposal] EqualConverter` <https://github.com/CommunityToolkit/Maui/issues/60>
- `[Proposal] NotEqualConverter` <https://github.com/CommunityToolkit/Maui/issues/73>

Equal and NotEqual converters

---

docs/maui/TOC.yml
docs/maui/behaviors/maximum-length-reached-behavior.md

- `[Proposal] Maximum Length Reached Behavior` <https://github.com/CommunityToolkit/Maui/issues/47>

Initial MaxLengthReachedBehavior page

---

docs/maui/TOC.yml
docs/maui/converters/double-to-int-converter.md

- `[Proposal] DoubleToIntConverter ` <https://github.com/CommunityToolkit/Maui/issues/57>

Add DoubleToIntConverter

---

docs/maui/TOC.yml
docs/maui/converters/equal-converter.md
docs/maui/converters/is-list-not-null-or-empty-converter.md
docs/maui/converters/is-list-null-or-empty-converter.md
docs/maui/converters/not-equal-converter.md
docs/maui/converters/text-case-converter.md

- `[Proposal] TextCaseConverter` <https://github.com/CommunityToolkit/Maui/issues/76>

Add TextCaseConverter

---

docs/maui/TOC.yml
docs/maui/converters/index.md
docs/maui/converters/inverted-bool-converter.md

- [Proposal] `InvertedBoolConverter ` <https://github.com/CommunityToolkit/Maui/issues/64>

Add InvertedBoolConverter

---

docs/maui/.template.md

An initial attempt at creating a template that can be used by contributors

Added initial maui toolkit template

---

docs/maui/TOC.yml
docs/maui/converters/color-to-black-or-white-converter.md
docs/maui/converters/color-to-color-for-text-converter.md
docs/maui/converters/color-to-gray-scale-color-converter.md
docs/maui/converters/color-to-inverse-color-converter.md
docs/maui/converters/index.md

- [Proposal] `ColorTo Color Converters ` <https://github.com/CommunityToolkit/Maui/issues/52> includes:
- `ColorToBlackOrWhiteConverter`
- `ColorToColorForTextConverter`
- `ColorToGrayScaleColorConverter`
- `ColorToInverseColorConverter`

ColorTo Color converters

---

docs/maui/TOC.yml
docs/maui/behaviors/maximum-length-reached-behavior.md
docs/maui/markup/extensions/absolute-layout-extensions.md
docs/maui/markup/extensions/visual-element-extensions.md

- [Proposal] `Behaviors VisualElement extension` <https://github.com/CommunityToolkit/Maui.Markup/issues/29>

Add Visual Element extensions

---

docs/TOC.yml
docs/dotnet/TOC.yml
docs/dotnet/index.md
docs/index.yml

FYI @Sergio0694 for review.
Adds info together from the Read me of the .NET Community Toolkit repo to form an initial landing page in this new repo here so we can have a better experience with our new landing page for docs.
I added new TOC/Index.yaml stuff as well to better highlight and branch out to our existing docs for the .NET and WCT.

Add an initial landing page for the .NET Community Toolkit

---

docs/index.yml
docs/maui/TOC.yml
docs/maui/behaviors/index.md
docs/maui/behaviors/maximum-length-reached-behavior.md
docs/maui/converters/index.md

Fills out the landing page a little more with our top level concepts

Added the index sections to the landing page

---

docs/maui/TOC.yml
docs/maui/markup/extensions/style.md

This PR adds docs for `CommunityToolkit.Maui.Markup.Style<T>`

Add `Style<T>` Docs

---

docs/maui/TOC.yml
docs/maui/behaviors/index.md
docs/maui/behaviors/user-stopped-typing-behavior.md

New doc with Index and TOC for the UserStoppedTypingBehavior for open proposal:
https://github.com/CommunityToolkit/Maui/issues/49

Added Doc for UserStoppedTypingBehavior

---

docs/index.yml

Adds a link to the the Views/index page on the landing page

Add Views to the landing page

---

docs/maui/TOC.yml
docs/maui/converters/bool-to-object-converter.md
docs/maui/converters/index.md

- [Proposal] `BoolToObjectConverter ` <https://github.com/CommunityToolkit/Maui/issues/50> includes:

BoolToObjectConverter

---

docs/maui/TOC.yml
docs/maui/converters/byte-array-to-image-source-converter.md
docs/maui/converters/index.md

- [Proposal] `ByteArrayToImageSourceConverter ` <https://github.com/CommunityToolkit/Maui/issues/51> includes:

ByteArrayToImageSourceConverter

---

docs/maui/TOC.yml
docs/maui/behaviors/characters-validation-behavior.md
docs/maui/behaviors/email-validation-behavior.md
docs/maui/behaviors/index.md
docs/maui/behaviors/required-string-validation-behavior.md
docs/maui/behaviors/text-validation-behavior.md
docs/maui/behaviors/uri-validation-behavior.md

- [Proposal] `RequiredStringValidationBehavior` <https://github.com/CommunityToolkit/Maui/issues/41>
- [Proposal] `TextValidationBehavior ` <https://github.com/CommunityToolkit/Maui/issues/42>
- [Proposal] `UriValidationBehavior ` <https://github.com/CommunityToolkit/Maui/issues/43>
- [Proposal] `CharactersValidationBehavior ` <https://github.com/CommunityToolkit/Maui/issues/37>
- [Proposal] `EmailValidationBehavior ` <https://github.com/CommunityToolkit/Maui/issues/38>

Add ValidationBehaviors

---

docs/maui/markup/extensions/bindable-object-extensions.md

This PR documents multi-binding, adding to `bindable-object-extensions.md`

Add Multi-Binding Docs

---

docs/maui/TOC.yml
docs/maui/extensions/color-conversion-extensions.md
docs/maui/extensions/index.md

- [Proposal] `ColorConversionExtensions` <https://github.com/CommunityToolkit/Maui/issues/89>

Add ColorConversionExtensions

---

docs/maui/extensions/color-animation-extensions.md

- [Proposal] `TextColorTo` <https://github.com/CommunityToolkit/Maui/issues/211>

Add TextColorTo

---

docs/maui/TOC.yml
docs/maui/behaviors/characters-validation-behavior.md
docs/maui/behaviors/email-validation-behavior.md
docs/maui/behaviors/event-to-command-behavior.md
docs/maui/behaviors/index.md
docs/maui/behaviors/masked-behavior.md
docs/maui/behaviors/maximum-length-reached-behavior.md
docs/maui/behaviors/numeric-validation-behavior.md
docs/maui/behaviors/progressbar-animation-behavior.md
docs/maui/behaviors/required-string-validation-behavior.md
docs/maui/behaviors/set-focus-when-entry-completed-behavior.md
docs/maui/behaviors/text-validation-behavior.md
docs/maui/behaviors/uri-validation-behavior.md
docs/maui/behaviors/user-stopped-typing-behavior.md

- [Proposal] `SetFocusOnEntryCompletedBehavior` <https://github.com/CommunityToolkit/Maui/issues/36>

Add SetFocusOnEntryCompletedBehavior

---

docs/maui/TOC.yml
docs/maui/markup/extensions/label-extensions.md
docs/maui/markup/markup.md

This PR adds the documentation for `LabelExtensions.cs`

Add Label extensions

---

docs/maui/TOC.yml
docs/maui/markup/extensions/text-alignment-extensions.md
docs/maui/markup/markup.md

This PR adds the docs for `TextAlignmentExtensions.cs`

Add TextAlignment Extensions

---

docs/maui/TOC.yml
docs/maui/markup/extensions/view-extensions.md
docs/maui/markup/markup.md

This PR adds the docs for `ViewExtensions.cs`

Add View Extensions

---

docs/maui/TOC.yml
docs/maui/converters/index.md
docs/maui/converters/variable-multi-value-converter.md

- [Proposal] `VariableMultiValueConverter` <https://github.com/CommunityToolkit/Maui/issues/77>

Add VariableMultiValueConverter

---

docs/maui/TOC.yml
docs/maui/markup/converters/func-converter.md
docs/maui/markup/converters/func-multi-converter.md
docs/maui/markup/markup.md

Adds docs pages for:
-`FuncConverter`
-`FuncMultiConverter`

Add FuncConverter docs

---

docs/maui/behaviors/email-validation-behavior.md

This PR documents the `Keyboard` enhancement added to `EmailValidationBehavior`: https://github.com/CommunityToolkit/Maui/pull/547

Document `EmailValidationBehavior`'s Updated `Keyboard` Enhancement

---

docs/maui/views/popup.md

Fixes issues #114 by adding some extra detail around the code behind requirements for a XAML based Popup.

Added detail on code behind requirements on Popup page

---

docs/maui/extensions/color-conversion-extensions.md

https://github.com/CommunityToolkit/Maui/pull/552

Use culture when convert colors

---

docs/maui/markup/extensions/automation-properties.md
docs/maui/markup/extensions/semantic-properties.md
docs/maui/markup/extensions/visual-element-extensions.md
docs/maui/markup/markup.md

Adds in docs for https://github.com/CommunityToolkit/Maui.Markup/pull/103

Added in the semantic properties docs

---

docs/maui/get-started.md

I was reading the document only to realise a lot of things broke just to find out you also had to append  ``.UseMauiCommunityToolkit()``.
i added it into the document so other people might not stumble over this

a small oversight in the setup section

---

docs/maui/behaviors/event-to-command-behavior.md

Based on discussion at https://github.com/CommunityToolkit/Maui/issues/569

Add note for when EventArgsConverter is required

---

docs/maui/TOC.yml
docs/maui/behaviors/statusbar-behavior.md
docs/maui/behaviors/statusbar-color-behavior.md

The feature is already merged on MCT.
- https://github.com/CommunityToolkit/Maui/pull/617

Created status bar docs

---

docs/maui/markup/extensions/grid-extensions.md

Edit line 157 "Buton" to "Button"

---

docs/maui/views/AvatarView.md

- See links on https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/views/avatarview , fixed them by removing the .md extension

Fix broken links by removing .md in AvatarView md

---

docs/maui/markup/extensions/bindable-object-extensions.md
docs/maui/markup/extensions/style.md

Adds the docs for PR: https://github.com/CommunityToolkit/Maui.Markup/pull/118

Added app theme docs

---

docs/maui/TOC.yml
docs/maui/layouts/StateContainer.md
docs/maui/layouts/index.md

Docs for the MCT StateContainer: https://github.com/CommunityToolkit/Maui/pull/673

Add StateContainer docs

---

docs/maui/converters/enum-to-bool-converter.md
docs/maui/options.md

Move to general `toolkit` for xaml

---

docs/maui/converters/enum-to-int-converter.md

Added note about ConverterParameter

---

docs/maui/views/Expander.md

Corrects the tooltip of the expander image

Fix tooltip for expander image

---

docs/maui/TOC.yml

Reference to DockLayout was missing from the TOC.

Added DockLayout.md to the Table of Contents

---

docs/maui/layouts/StateContainer.md

This PR updates `StateContainer` documentation to align with https://github.com/CommunityToolkit/Maui/pull/811

Update StateContainer Documentation

---

docs/maui/layouts/StateContainer.md

This feature hasn't been released yet, whoops

Revert "Update StateContainer Documentation"

---

docs/TOC.yml
docs/diagnostics/Guard.md
docs/diagnostics/Introduction.md
docs/diagnostics/ThrowHelper.md

This PR ports the Diagnostics docs. Haven't updated the links to the generated docs yet, as I think that's for later?

Port CommunityToolkit.Diagnostics docs

---

docs/index.yml

Small follow up, ooops forgot to update these 😅

Fix links of the index page

---

docs/maui/markup/extensions/bindable-object-extensions.md
docs/maui/markup/extensions/style.md
docs/maui/markup/theming.md

Additional docs to support the changes in https://github.com/CommunityToolkit/Maui.Markup/pull/167

Added an initial page on theming

---

docs/mvvm/generators/errors/MVVMTK0032.md
docs/mvvm/generators/errors/MVVMTK0033.md
docs/mvvm/generators/errors/MVVMTK0034.md
docs/mvvm/generators/errors/MVVMTK0035.md
docs/mvvm/generators/errors/TOC.yml

Add docs for new MVVM Toolkit diagnostics

---

docs/maui/views/Expander.md

Reverts MicrosoftDocs/CommunityToolkit#216

Revert "Update Expander NotSupported notes"

---

docs/mvvm/generators/errors/MVVMTK0008.md

Just correcting the ending tag for LangVersion

Small typo in language version code sample

---

docs/maui/behaviors/icon-tint-color-behavior.md

Adds point around Windows not being supported plus fixes path to repository code.

Add icon tint behavior improvements

---

docs/index.yml

Adds the missing concepts to the main landing page

Added the index pages for all key concepts

---

docs/maui/TOC.yml
docs/maui/views/index.md
docs/maui/views/semantic-order-view.md

Covers:
- Proposal https://github.com/CommunityToolkit/Maui/issues/116
- PR https://github.com/CommunityToolkit/Maui/pull/1011

Added an initial page about the SemanticOrderView

---

docs/maui/views/Expander.md

Redo of #216 which I merged too soon...

Update Expander NotSupported notes (#216)

---

docs/mvvm/generators/ObservableProperty.md
docs/mvvm/generators/RelayCommand.md

This PR adds more info to the docs to call out features mentioned in [the release blog post](https://devblogs.microsoft.com/dotnet/announcing-the-dotnet-community-toolkit-820/).

Update MVVM Toolkit docs for 8.2.0 release

---

docs/mvvm/generators/errors/MVVMTKCFG0001.md
docs/mvvm/generators/errors/MVVMTKCFG0002.md
docs/mvvm/generators/errors/TOC.yml

This PR adds docs on two new warnings produced by the MVVM Toolkit.

Add docs on MVVMTKCFG0001 and MVVMTKCFG0002

---

docs/mvvm/generators/errors/MVVMTKCFG0002.md

Fix typo in MVVMTKCFG0002 docs

---

docs/maui/essentials/file-saver.md
docs/maui/essentials/folder-picker.md

Fix links to file saver and folder picker apis

---

docs/maui/get-started.md

Tweaked sample app description

---

docs/maui/behaviors/icon-tint-color-behavior.md

Correct the copy/paste issue of an incorrect variable name

---

docs/mvvm/generators/errors/MVVMTK0040.md
docs/mvvm/generators/errors/TOC.yml

See https://github.com/CommunityToolkit/dotnet/pull/735.

Add docs for MVVMTK0040 error

---

docs/maui/essentials/speech-to-text.md

https://github.com/CommunityToolkit/Maui/pull/1382

Update SpeechToText #1382

---

docs/maui/behaviors/select-all-text-behavior.md

Hello @pictos and @brminnick ,
I just created the documentation for the **SelectAllText** behavior.
Let me know if it looks OK or if we need to update it.
Regards,
Victor

Created the Select All Text Behavior documentation

---

docs/maui/views/DrawingView.md

https://github.com/CommunityToolkit/Maui/pull/1440

DrawingView add events

---

docs/maui/index.md

Add details on reporting issues

---

docs/maui/essentials/folder-picker.md

Provide info on cancellationtoken

---

docs/maui/TOC.yml
docs/maui/views/semantic-order-view.md

Add title to SemanticOrderView and remove from extensions section

---

docs/maui/essentials/file-saver.md
docs/maui/essentials/folder-picker.md

Introduces details on how to work with App Sandbox for macOS.

Add details on app sandbox permissions

---

docs/maui/views/semantic-order-view.md

Fix invalid XAML in SemanticOrderView docs

---

docs/docfx.json

ms.prod has been deprecated and replaced with ms.service

ms.prod to ms.service

---

docs/maui/TOC.yml
docs/maui/behaviors/index.md
docs/maui/behaviors/statusbar-behavior.md

There are several mismatches between the TOC and the tables in the index.md pages.

Fix mismatches between TOC and index pages.

---

docs/maui/views/MediaElement.md

Aims to detail a known issue and the workaround coming out of https://github.com/CommunityToolkit/Maui/pull/1692

Add warning around known issue with full-screen support

---

docs/docfx.json

Fix the metadata warning about ms.topic.

Add ms.topic

---

docs/maui/get-started.md

Updating Getting Started for the change in https://github.com/CommunityToolkit/Maui/pull/1771

Update Maps Getting Started

---

docs/maui/TOC.yml
docs/maui/behaviors/animation-behavior.md
docs/maui/behaviors/icon-tint-color-behavior.md
docs/maui/behaviors/image-touch-behavior.md
docs/maui/behaviors/index.md
docs/maui/behaviors/touch-behavior.md
docs/maui/markup/markup.md

Provides documentation for https://github.com/CommunityToolkit/Maui/pull/1673

Add TouchBehavior and ImageTouchBehavior documentation

---

docs/maui/behaviors/touch-behavior.md
docs/maui/views/DrawingView.md
docs/maui/views/MediaElement.md

Remove usage of obsolete *AndExpand layout options

---

docs/maui/behaviors/icon-tint-color-behavior.md

Replace Tintcolor to TintColor

---

.github/workflows/check-for-build-warnings.yml

As discussed, this adds status checks on PRs for the docs to surface warnings/errors a bit better without adding the noise of the comments in the PR itself.

Adds status checks for docs changes PRs

---

docs/maui/behaviors/touch-behavior.md

As discussed in the MCT discord, I have written a migration guide that can both help people migrating from XCT aswell as documenting how we can set the binding context on the behavior
This is my first time contributing to microsoft docs so I am very much open to advise & critique of my writing. I am used to writing technical documentation for internal use so I am not sure if my tone & examples, plus use of links is appropriate. Any & all critiques will be graciously accepted 😇

Added Touch Behavior Migration Guide

---

docs/maui/views/MediaElement.md

Update for Media Element initialization as per PR: https://github.com/CommunityToolkit/Maui/pull/1814

Update MediaElement initialization on Android

---

docs/maui/converters/compare-converter.md

Documentation for https://github.com/CommunityToolkit/Maui/pull/1841

Add example of how to sub-class the converter and simplify XAML

---

docs/maui/views/Popup.md

Update Popup events API descriptions

---

docs/maui/get-started.md

Correct the using statement for MediaElement getting started

---

docs/maui/converters/bool-to-object-converter.md

Correct the bool to object converter example

---

docs/maui/markup/extensions/bindable-layout-extensions.md

Correct the ItemsSource sample

---

docs/maui/essentials/apptheme-resources.md

Fix broken AppTheme link

---

docs/maui/native-library-interop/get-started.md
docs/maui/native-library-interop/index.md

Small tweaks to update instructions and fix typos

Update NativeLibraryInterop docs

---

docs/maui/views/MediaElement.md

Fix Android service casing for .NET MAUI MediaElement

---

docs/maui/essentials/speech-to-text.md

Remove invalid code from speech-to-text.md

---

docs/maui/markup/extensions/object-extensions.md

Fix typo in object-extensions.md

---

docs/maui/views/MediaElement.md

Updated reference to library location and name of organization for android support libraries. We used to xamarin team but we have switched to using the android support library. I also updated the android manifest references to reflect required changes.

Update for media3 for media element

---

docs/maui/views/Expander.md

https://github.com/CommunityToolkit/Maui/pull/1567/files

Fix Expander docs for 1567

---

docs/maui/converters/compare-converter.md

Correct closing tags on CompareConverter page

---

docs/maui/markup/markup.md

Include using statement in bigger example

---

docs/high-performance/Span2D.md

Change the index in order to:
- match the code with the expected outcome (that is specified in the comment right below it)
- not throw the IndexOutOfRangeException anymore 🤦‍♂️
✌

Fix IndexOutOfRangeException ⚒

---

docs/maui/views/popup/popup-result.md

Fixes the xmlns for `system`, corrects the parameters provided and the method being called.

Popup fixes
