docs/maui/TOC.yml, docs/maui/markup/markup.md
Adding an overview of the CommunityToolkit.Maui.Markup package ready for the rest of the content to follow.
This PR is based off the content at: https://docs.microsoft.com/en-gb/xamarin/community-toolkit/markup with the following differences:
- Migrate from Xamarin.Forms to Maui details.
- Only focus on an overview allowing us to dive in to more specific topics (e.g. Data binding, etc.) in separate pages
=> Initial Maui.Markup overview

docs/maui/TOC.yml, docs/maui/converters/index.md
@davidbritch @brminnick @jfversluis
Just trying out a landing page for converters that links over to the .NET MAUI docs. The links in the table currently link to our written docs but I suspect these could quite easily link out to the API docs instead. What do you think?
=> Trying out a landing page for Converters

docs/maui/TOC.yml, docs/maui/markup/extensions/placeholder-extensions.md
This PR adds the Maui.Markup docs for the `IPlaceholder` extension methods added in this PR: https://github.com/CommunityToolkit/Maui.Markup/pull/44/files
=> Add `IPlaceholder` Extensions Docs for Maui.Markup

docs/maui/TOC.yml, docs/maui/markup/extensions/image-extensions.md, docs/maui/markup/extensions/placeholder-extensions.md
This PR adds the documentation for the `IImage` extensions added in this Maui.Markup PR: https://github.com/CommunityToolkit/Maui.Markup/pull/46
It also fixes a typo in `placeholder-extensions.md`.
=> Add `IImage` Extensions Docs

docs/maui/TOC.yml, docs/maui/behaviors/index.md, docs/maui/behaviors/progressbar-animation-behavior.md
New docs page for the ProgressBarAnimationBehavior along with the Index and TOC changes...
This will close [Proposal] ProgressBar Animation Behavior https://github.com/CommunityToolkit/Maui/issues/48
There is an issue that I can see with the docs in that for the Docs to show a working example I had to leave the Easing out as it looks like there is no bindable property. 
In the MCT sample app there is a note in the page code behind file:
https://github.com/CommunityToolkit/Maui/blob/main/samples/CommunityToolkit.Maui.Sample/Pages/Behaviors/ProgressBarAnimationBehaviorPage.xaml.cs
Not sure if we should mention this limitation in the docs or look at fixing the issue so for now I have left it out and looking for guidance.
=> Added doc page for the ProgressBarAnimationBehavior

docs/maui/behaviors/characters-validation-behavior.md, docs/maui/behaviors/email-validation-behavior.md, docs/maui/behaviors/masked-behavior.md, docs/maui/behaviors/maximum-length-reached-behavior.md, docs/maui/behaviors/numeric-validation-behavior.md, docs/maui/behaviors/required-string-validation-behavior.md, docs/maui/behaviors/text-validation-behavior.md, docs/maui/behaviors/uri-validation-behavior.md
This is a hot fix that fixes the broken link to the API code.
=> Fixed paths to the API code

docs/breadcrumb/toc.yml
Changes the breadcrumb to show `.NET MAUI` instead of just `MAUI`
=> Fix toolkit name to include .NET in the breadcrumb

docs/maui/TOC.yml, docs/maui/extensions/index.md, docs/maui/extensions/servicecollection-extensions.md
Documentation for CommunityToolkit.Maui.IServiceCollectionExtensions in PR [#494](https://github.com/CommunityToolkit/Maui/pull/494)
- Updated TOC
- Updated /extensions/index.md
- Added new ServiceCollectionExtensions page
NOTE: Markdownlint rule MD024 was set to allow_different_nesting = true at the page level due to multiple extension methods requiring documentation for parameters of same name, type, etc.
=> CommunityToolkit.Maui.IServiceCollectionExtensions 

docs/maui/index.md
This change links to the .NET MAUI supported versions page to show which platforms and the minimum versions that the toolkit supports.
=> Detail on supported platforms

docs/mvvm/generators/INotifyPropertyChanged.md
[INotifyPropertyChanged](https://docs.microsoft.com/en-us/dotnet/api/communitytoolkit.mvvm.componentmodel.INotifyPropertyChangedAttribute): implements the interface and adds helper methods to set properties and raise the **veents.**
> **veents.**
This line has a typo error.
=> Typo error in "How to use them" section

docs/mvvm/generators/RelayCommand.md
From my understanding the argument of `NotifyCanExecuteChangedFor` has to be the command.
=> Docs: Change example NotifyCanExecuteChangedFor argument

contributing/contributing-maui.md, docs/maui/markup/extensions/label-extensions.md
**Global effort for the Microsoft Learn platform rebrand**
The Microsoft team is applying changes to content for the Microsoft Learn platform rebrand. Changes include modifications to current Microsoft Learn and Microsoft Docs terminology as well as associated domain name and content URL path changes.
**DO NOT MERGE THIS PULL REQUEST WHILE IN DRAFT STATUS!** Some of the changes to links and other content are not valid until after go-live.
Please review this draft PR and provide any necessary comments as soon as possible. Because these fixes are tightly scoped, we have approval to automatically merge these changes to the default branch for publication.
This PR was generated via DocuTune. It includes only targeted fixes and minor formatting adjustments.
CorrelationId: …
=> [BULK UPDATE] DocuTune - Rebranding links

docs/maui/markup/markup.md
This PR removes the duplicated non-fluent example that can be confusing + off-putting to developers visiting the docs for the first time: https://learn.microsoft.com/dotnet/communitytoolkit/maui/markup/markup#in-depth-example
As seen in the screenshot, below, the actual C# Markup example is not immediately shown in this section, forcing the user to scroll down to find it. A user may assume that the (removed in this PR) duplicated example is the actual C# Markup example.
=> Remove Duplicated `ContentPage` Example

docs/maui/TOC.yml, docs/maui/behaviors/email-validation-behavior.md, docs/maui/markup/extensions/bindable-object-extensions.md, docs/maui/markup/extensions/object-extensions.md
This PR adds docs for the newly created `ObjectExtends.cs` class introduced in this PR: https://github.com/CommunityToolkit/Maui.Markup/pull/131
**Note:** This PR will be merged upon release of `CommunityToolkit.Maui.Markup v1.3.0`
=> [Maui.Markup] Add `ObjectExtension` Docs

docs/maui/TOC.yml
Adds the missing links to `IsNullConverter` and `IsNotNullConverter` as per #158
=> Included the null based converters in the TOC

docs/maui/behaviors/event-to-command-behavior.md
Improves the details of grabbing the event args through the `EventToCommandBehavior` class as previously discussed at https://github.com/CommunityToolkit/Maui/issues/569
=> Include section on generic type for event args

docs/maui/behaviors/statusbar-behavior.md
This PR adds an info to devs where they should pay attention when changing the StatusBarColor or Style using the methods on `MCT.Core`.
This can be removed in the future, when we implement a way to queue the calls until everything is properly initialized on .NET MAUI.
=> Added a warning on the method usage.

docs/maui/alerts/toast.md, docs/maui/index.md
This PR updates the additional platform support on the CommunityToolkit and the content links to the .NET MAUI supported versions page.
Tizen support PR https://github.com/CommunityToolkit/Maui/pull/692/ is planned to be merged and released likely on 08 November.
=> Add Tizen support on docs

docs/maui/views/DrawingView.md
Probably due to the length of an image, newline is required when it is seen in the wide screen.
<image src="https://user-images.githubusercontent.com/14328614/203749653-3b153030-5364-4c46-a89a-6c4e8bc9a58b.png" width="600" />
=> Fix newline on DrawingView

docs/mvvm/MigratingFromMvvmBasic.md, docs/mvvm/MigratingFromMvvmLight.md
Closes #156.
These were referring to the WCT, this PR updates them to reflect the new name.
=> Update migration docs for the MVVM Toolkit

docs/index.yml
This PR removes the accidental leading `/` characters, which are breaking navigation.
=> Fix paths of .NET Community Toolkit index files

docs/mvvm/ObservableValidator.md
* Style (name) with backticks in (This method receives the `name` property value and ...).
* Remove (.) before (and) in (... by implementing a custom `[ValidationAttribute]` and then...).
=> Typo fix - update to ObservableValidator article

docs/maui/behaviors/user-stopped-typing-behavior.md, docs/maui/converters/item-tapped-eventargs-converter.md, docs/maui/layouts/StateContainer.md, docs/maui/markup/extensions/bindable-layout-extensions.md, docs/maui/markup/extensions/bindable-object-extensions.md, docs/maui/markup/extensions/itemsview-extensions.md, docs/maui/markup/markup.md
Hey @bijington! I updated the new binding docs a bit, adding two way bindings, where necessary, in our examples.
I also added `mode: BindingMode.OneTime` when binding to `ICommand`. It gives a small performance bump since `ICommand`s are usually read-only properties in 99.9% of apps and thus bindings to `ICommand` never change.
I also changed our one-way binding example to use `Label.TextProperty` instead of `Entry.TextProperty`. I think using `Label.TextProperty`, which defaults to a `BindingMode.OneWay` already helps simplify the example and may be more intuitive to a new dev.
=> Add TwoWay Bindings, Use BindingMode.OneTime for ICommand

docs/mvvm/generators/errors/MVVMTK0035.md, docs/mvvm/generators/errors/MVVMTK0036.md, docs/mvvm/generators/errors/TOC.yml
=> Add docs for MVVMTK0036

docs/high-performance/Ref.md
There were two links with the link text Ref&<T>. Fixed.
=> Removed erroneous ampersand in 2 links (Ref&<T>)

docs/maui/converters/enum-to-bool-converter.md
=> Fix typo in enum-to-bool-converter docs

docs/mvvm/generators/errors/MVVMTK0039.md, docs/mvvm/generators/errors/TOC.yml
See https://github.com/CommunityToolkit/dotnet/pull/714.
=> Add docs for MVVMTK0039

docs/maui/get-started.md, docs/maui/views/Map.md, docs/maui/views/index.md
Adds some brief documentation for the .NET MAUI Community Toolkit Windows Maps. Basically the get started as that is an extra step from the regular .NET MAUI Maps and then refer to the .NET MAUI documentation for the actual APIs.
=> Add .NET MAUI Map for Windows docs

docs/maui/markup/extensions/bindable-object-extensions.md
We can remove this warning now that the example above it uses Typed Bindings and will not use reflection
=> Remove Obsolete Reflection Warning

docs/maui/views/MediaElement.md
Adds a note to the .NET MAUI Community Toolkit `MediaElement` docs that the `embed://` and `filesystem://` prefixes are only to be meant for use in XAML.
Fixes https://github.com/CommunityToolkit/Maui/issues/1122
=> Add note for MediaElement embed:// and filesystem://

docs/maui/views/MediaElement.md
Adds a little bit clearer which package is needed for MediaElement and links to the right tab on the Getting Started page.
Fixes #301
=> More clearly state which NuGet is needed for MediaElement

docs/maui/extensions/keyboard-extensions.md
I think the documentation is not quite right for KeyboardExtensions. 
I'm using CommunityToolkit.Maui.Core 6.0.0 and my IDE is telling me the namespace should be: 
```using CommunityToolkit.Maui.Core.Platform;```
=> Fix documentation for KeyboardExtension namespace

docs/maui/extensions/servicecollection-extensions.md, docs/maui/views/popup.md
Aims at covering the documentation for the new popup service at: https://github.com/CommunityToolkit/Maui/pull/1165
=> Add in a section to cover the PopupService

docs/maui/views/popup.md
This is aimed at providing a little bit of detail to aid the completion of https://github.com/CommunityToolkit/Maui/pull/1351. In truth we probably don't need too much detail given this is 'just how .NET MAUI controls' work.
=> Provide style documentation section for Popups

docs/maui/views/MediaElement.md
The link to the ExoPlayer Documentation was according to the content of its page out of date and developer.android.com was recommended instead. 
Here is the message that is shown for the current link:
=> Update Link to ExoPlayer in MediaElement.md

docs/maui/behaviors/animation-behavior.md
Adds a note on why the `AnimateCommand` works and updates the sample to pass in a `CancellationToken`
=> Update AnimateCommand sample

docs/maui/essentials/speech-to-text.md
=> Fix link to ISpeechToText in Community Toolkit repository

docs/maui/views/MediaElement.md
The sample code for handling the silent switch on iDevices didn't compile as-is.
This PR fully qualifies the type names so that it's more clear what the full solution is in this case.
Fixes #417
=> Fully qualify AVAudioSession in sample code

docs/maui/views/camera-view.md
Typo in Camera documentation for Stop Preview.
See #444  for details.
Current copy:
The CameraView provides the ability to programmatically **start** the preview from the camera. This is possible through both the StopCameraPreview method or the StopCameraPreviewCommand.
Expected copy:
The CameraView provides the ability to programmatically **stop** the preview from the camera. This is possible through both the StopCameraPreview method or the StopCameraPreviewCommand.
=> Typo in Camera documentation for Stop Preview: issue #444

docs/maui/includes/behavior-bindings.md, docs/maui/includes/communitytoolkit-converter.md, docs/maui/includes/math-expression-operations.md, docs/maui/includes/toast-snackbar-setup.md, docs/maui/includes/validation-behavior.md, docs/maui/includes/xaml-usage.md
Mark include files as include files, so that they aren't also built as unique docs in their own right.
=> Mark include files as include files

docs/maui/views/MediaElement.md
See: https://github.com/CommunityToolkit/Maui/pull/1950
Adds a note to the `MediaHeight` & `MediaWidth` properties about when the value might not be reported.
=> Tweak MAUI MediaElement `MediaHeight` & `MediaWidth` API description

docs/maui/markup/extensions/bindable-object-extensions.md
This PR simplifies the initialization syntax of Complex (Nested) Bindings, leveraging Collection Expressions. 
It also provides a small performance improvement as the Compiled Expression always compiles down to the most efficient code. Here is the compiler output for the Collection Expression used in this example in the docs:
```cs
new ValueTuple<Func<ViewModel, object>, string>[2]
{
new ValueTuple<Func<ViewModel, object>, string>((Func<ViewModel, object>)((ViewModel vm) => vm), "NestedObject"),
new ValueTuple<Func<ViewModel, object>, string>((Func<ViewModel, object>)((ViewModel vm) => vm. NestedObject), "Text")
},
```
=> Use Collection Expressions for Complex (Nested) Bindings

docs/docfx.json
This PR sets a global `ms.date` value so that every article in the docset has a valid `ms.date` value.
=> Set a global ms.date

docs/maui/markup/extensions/bindable-object-extensions.md, docs/maui/markup/extensions/text-alignment-extensions.md
---
**DO NOT MERGE THIS UNTIL THIS PR ON `COMMUNITYTOOLKIT.MAUI.MARKUP` HAS BEEN MERGED: https://github.com/CommunityToolkit/Maui.Markup/pull/324**
---
This PR updates the `CommunityToolkit.Maui.Markup` docs for .NET 9. 
In .NET 9, using a `string` path for bindings is no longer supported. We've also removed all `[Obsoelete]` extension methods (e.g. `ClickGestureRecognizer`).
=> Update `CommunityToolkit.Maui.Markup` Docs for .NET 9

docs/diagnostics/Guard.md
https://github.com/CommunityToolkit/dotnet/blob/657c6971a8d42655c648336b781639ed96c2c49f/src/CommunityToolkit.Diagnostics/Guard.String.cs#L76
=> Fix method name in Guard API

docs/maui/views/MediaElement.md
android:stopWithTask requires `="true"` to work. This matches the full example further down.
=> Fixed typo with android:stopWithTask

docs/maui/views/MediaElement.md
As seen in .NET MAUI's [2485](https://github.com/CommunityToolkit/Maui/issues/2485) bug ticket, this configuration can prevent a `Java.Lang.AbstractMethodError Message=abstract method "void androidx.media3.common.Player$Listener.onSurfaceSizeChanged(int, int)"` from crashing the app.
=> Add minimum Android version requirements to MediaElement.md

docs/maui/native-library-interop/get-started.md
Points the overview link to index.md in the native interop folder rather than the MAUI Community Toolkit.
=> Correctly link to the index.md at the same level

docs/maui/platform-specific/DialogFragment-customization.md
Docs related to:
- https://github.com/CommunityToolkit/Maui/pull/2413
=> DialogFragment service docs

docs/maui/index.md
This increases the minimum versions provided by the .NET MAUI template at: https://github.com/dotnet/maui/blob/main/src/Templates/src/templates/maui-mobile/MauiApp.1.csproj
Fixes toolkit issue: https://github.com/CommunityToolkit/Maui/issues/2528
=> Increase the minimum apple versions

docs/maui/converters/item-tapped-eventargs-converter.md
Updated to use Binding context with a reference since EventToCommandBehavior fails silently without the context.  I copied this from the sample apps but it wasn't in the docs
=> Update Item Tapped Eventargs Converter docs

docs/windows/Animations/ConnectedAnimations.md, docs/windows/Collections/AdvancedCollectionView.md, docs/windows/Extensions/DispatcherQueueTimerExtensions.md, docs/windows/Extensions/ListViewExtensions.md, docs/windows/Media/AttachedCardShadow.md, docs/windows/Media/Brushes.md, docs/windows/Media/EffectAnimations.md, docs/windows/Media/PipelineBrush.md, docs/windows/Media/PipelineVisualFactory.md, docs/windows/Primitives/SwitchPresenter.md, docs/windows/TOC.yml
Doc updates for WCT 8.2 Release
FYI @Arlodotexe
Some notes on bumps in the process here from the script update that was needed are in this PR here: https://github.com/CommunityToolkit/Tooling-Windows-Submodule/pull/280
=> Updates for docs from WCT 8.2 Release

docs/high-performance/Memory2D.md
Fix a typo to use the correct type
=> Fix a typo

docs/maui/views/Popup.md
This PR documents `DefaultPopupSettings` and `DefaultPopupOptionsSettings` created in this PR: https://github.com/CommunityToolkit/Maui/pull/2759
=> Add `DefaultPopupSettings` and `DefaultPopupOptionsSettings`
